baseURL: https://gemaakbr.netlify.app/
languageCode: en-us
title: "Home"
theme: "PaperMod"

params:
    defaultTheme: auto 

    homeInfoParams:
        Title: Hello There!
        Content: I'm Muchammad Gema Akbar, you can call me Gema

    socialIcons: # optional
        - name: "email"
          url: "mailto:gemaakbar213@gmail.com"
        - name: "github"
          url: "https://github.com/gemm123"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/gemaakbar07/"
        - name: "medium"
          url: "https://medium.com/@gemaakbar213"
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary